// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sie.proto

package sie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SieType is the SIE format type/level (#SIETYP). The values match the numeric
// SIE codes 1-4.
type SieType int32

const (
	SieType_SIE_TYPE_UNSPECIFIED SieType = 0
	// Year-end account balances (1).
	SieType_SIE_TYPE_YEAR_END_BALANCES SieType = 1
	// Period account balances (2).
	SieType_SIE_TYPE_PERIOD_BALANCES SieType = 2
	// Period balances broken down by object/dimension (3).
	SieType_SIE_TYPE_OBJECT_BALANCES SieType = 3
	// Full transactions (4).
	SieType_SIE_TYPE_TRANSACTIONS SieType = 4
)

// Enum value maps for SieType.
var (
	SieType_name = map[int32]string{
		0: "SIE_TYPE_UNSPECIFIED",
		1: "SIE_TYPE_YEAR_END_BALANCES",
		2: "SIE_TYPE_PERIOD_BALANCES",
		3: "SIE_TYPE_OBJECT_BALANCES",
		4: "SIE_TYPE_TRANSACTIONS",
	}
	SieType_value = map[string]int32{
		"SIE_TYPE_UNSPECIFIED":       0,
		"SIE_TYPE_YEAR_END_BALANCES": 1,
		"SIE_TYPE_PERIOD_BALANCES":   2,
		"SIE_TYPE_OBJECT_BALANCES":   3,
		"SIE_TYPE_TRANSACTIONS":      4,
	}
)

func (x SieType) Enum() *SieType {
	p := new(SieType)
	*p = x
	return p
}

func (x SieType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SieType) Descriptor() protoreflect.EnumDescriptor {
	return file_sie_proto_enumTypes[0].Descriptor()
}

func (SieType) Type() protoreflect.EnumType {
	return &file_sie_proto_enumTypes[0]
}

func (x SieType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SieType.Descriptor instead.
func (SieType) EnumDescriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{0}
}

// AccountType is the account classification (#KTYP).
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	// Asset (SIE code "T", tillgång).
	AccountType_ACCOUNT_TYPE_ASSET AccountType = 1
	// Liability, including equity (SIE code "S", skuld).
	AccountType_ACCOUNT_TYPE_LIABILITY AccountType = 2
	// Expense (SIE code "K", kostnad).
	AccountType_ACCOUNT_TYPE_EXPENSE AccountType = 3
	// Income (SIE code "I", intäkt).
	AccountType_ACCOUNT_TYPE_INCOME AccountType = 4
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_ASSET",
		2: "ACCOUNT_TYPE_LIABILITY",
		3: "ACCOUNT_TYPE_EXPENSE",
		4: "ACCOUNT_TYPE_INCOME",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_ASSET":       1,
		"ACCOUNT_TYPE_LIABILITY":   2,
		"ACCOUNT_TYPE_EXPENSE":     3,
		"ACCOUNT_TYPE_INCOME":      4,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_sie_proto_enumTypes[1].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_sie_proto_enumTypes[1]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{1}
}

// Decimal is a fixed-point monetary amount stored as an integer number of
// hundredths ("cents"). Money can't be represented exactly as a float, so we
// keep the underlying int64 and add convenience conversions on top (see the
// hand-written methods in the generated package).
type Decimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cents         int64                  `protobuf:"varint,1,opt,name=cents,proto3" json:"cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	mi := &file_sie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_sie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{0}
}

func (x *Decimal) GetCents() int64 {
	if x != nil {
		return x.Cents
	}
	return 0
}

// Document is a parsed SIE file: company metadata, its chart of accounts and
// the vouchers within the covered financial year.
type Document struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramName    string                 `protobuf:"bytes,1,opt,name=program_name,json=programName,proto3" json:"program_name,omitempty"`
	ProgramVersion string                 `protobuf:"bytes,2,opt,name=program_version,json=programVersion,proto3" json:"program_version,omitempty"`
	GeneratedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	GeneratedBy    string                 `protobuf:"bytes,4,opt,name=generated_by,json=generatedBy,proto3" json:"generated_by,omitempty"`
	// SIE format type/level (#SIETYP).
	SieType SieType `protobuf:"varint,5,opt,name=sie_type,json=sieType,proto3,enum=sie.v1.SieType" json:"sie_type,omitempty"`
	// Company registration number (#ORGNR).
	OrganisationNumber string `protobuf:"bytes,6,opt,name=organisation_number,json=organisationNumber,proto3" json:"organisation_number,omitempty"`
	CompanyName        string `protobuf:"bytes,7,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	// Chart-of-accounts standard (#KPTYP), e.g. "EUBAS97".
	ChartOfAccounts    string                 `protobuf:"bytes,8,opt,name=chart_of_accounts,json=chartOfAccounts,proto3" json:"chart_of_accounts,omitempty"`
	Accounts           []*Account             `protobuf:"bytes,9,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Vouchers           []*Voucher             `protobuf:"bytes,10,rep,name=vouchers,proto3" json:"vouchers,omitempty"`
	FinancialYearStart *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=financial_year_start,json=financialYearStart,proto3" json:"financial_year_start,omitempty"`
	FinancialYearEnd   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=financial_year_end,json=financialYearEnd,proto3" json:"financial_year_end,omitempty"`
	Dimensions         []*Dimension           `protobuf:"bytes,13,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_sie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_sie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *Document) GetProgramVersion() string {
	if x != nil {
		return x.ProgramVersion
	}
	return ""
}

func (x *Document) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *Document) GetGeneratedBy() string {
	if x != nil {
		return x.GeneratedBy
	}
	return ""
}

func (x *Document) GetSieType() SieType {
	if x != nil {
		return x.SieType
	}
	return SieType_SIE_TYPE_UNSPECIFIED
}

func (x *Document) GetOrganisationNumber() string {
	if x != nil {
		return x.OrganisationNumber
	}
	return ""
}

func (x *Document) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Document) GetChartOfAccounts() string {
	if x != nil {
		return x.ChartOfAccounts
	}
	return ""
}

func (x *Document) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *Document) GetVouchers() []*Voucher {
	if x != nil {
		return x.Vouchers
	}
	return nil
}

func (x *Document) GetFinancialYearStart() *timestamppb.Timestamp {
	if x != nil {
		return x.FinancialYearStart
	}
	return nil
}

func (x *Document) GetFinancialYearEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.FinancialYearEnd
	}
	return nil
}

func (x *Document) GetDimensions() []*Dimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

// Account is a single account in the chart of accounts, with its opening and
// closing balances for the covered financial year.
type Account struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Number int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// Account classification (#KTYP).
	Type           AccountType `protobuf:"varint,2,opt,name=type,proto3,enum=sie.v1.AccountType" json:"type,omitempty"`
	Name           string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OpeningBalance *Decimal    `protobuf:"bytes,4,opt,name=opening_balance,json=openingBalance,proto3" json:"opening_balance,omitempty"`
	ClosingBalance *Decimal    `protobuf:"bytes,5,opt,name=closing_balance,json=closingBalance,proto3" json:"closing_balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_sie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_sie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Account) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetOpeningBalance() *Decimal {
	if x != nil {
		return x.OpeningBalance
	}
	return nil
}

func (x *Account) GetClosingBalance() *Decimal {
	if x != nil {
		return x.ClosingBalance
	}
	return nil
}

// Voucher is a dated, balanced set of postings (#VER).
type Voucher struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number within the series.
	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	// Voucher series (#VER), e.g. "A".
	Series string `protobuf:"bytes,2,opt,name=series,proto3" json:"series,omitempty"`
	// Accounting date.
	Date        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Date the voucher was recorded (regdatum).
	RegisteredDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_date,json=registeredDate,proto3" json:"registered_date,omitempty"`
	Postings       []*Posting             `protobuf:"bytes,6,rep,name=postings,proto3" json:"postings,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Voucher) Reset() {
	*x = Voucher{}
	mi := &file_sie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Voucher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voucher) ProtoMessage() {}

func (x *Voucher) ProtoReflect() protoreflect.Message {
	mi := &file_sie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voucher.ProtoReflect.Descriptor instead.
func (*Voucher) Descriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{3}
}

func (x *Voucher) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Voucher) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *Voucher) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Voucher) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Voucher) GetRegisteredDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredDate
	}
	return nil
}

func (x *Voucher) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

// Posting is a single amount booked against an account within a voucher.
type Posting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber int32                  `protobuf:"varint,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Dimensions    []*Dimension           `protobuf:"bytes,2,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	Amount        *Decimal               `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posting) Reset() {
	*x = Posting{}
	mi := &file_sie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posting) ProtoMessage() {}

func (x *Posting) ProtoReflect() protoreflect.Message {
	mi := &file_sie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posting.ProtoReflect.Descriptor instead.
func (*Posting) Descriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{4}
}

func (x *Posting) GetAccountNumber() int32 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *Posting) GetDimensions() []*Dimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *Posting) GetAmount() *Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

// Dimension is an accounting object (#OBJEKT) — e.g. a cost centre or project —
// attached to a posting, or a dimension definition at document level.
type Dimension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dimension number.
	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// Object identifier within the dimension.
	ObjectCode string `protobuf:"bytes,2,opt,name=object_code,json=objectCode,proto3" json:"object_code,omitempty"`
	// Object display name.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimension) Reset() {
	*x = Dimension{}
	mi := &file_sie_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimension) ProtoMessage() {}

func (x *Dimension) ProtoReflect() protoreflect.Message {
	mi := &file_sie_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimension.ProtoReflect.Descriptor instead.
func (*Dimension) Descriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{5}
}

func (x *Dimension) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Dimension) GetObjectCode() string {
	if x != nil {
		return x.ObjectCode
	}
	return ""
}

func (x *Dimension) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_sie_proto protoreflect.FileDescriptor

const file_sie_proto_rawDesc = "" +
	"\n" +
	"\tsie.proto\x12\x06sie.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1f\n" +
	"\aDecimal\x12\x14\n" +
	"\x05cents\x18\x01 \x01(\x03R\x05cents\"\x89\x05\n" +
	"\bDocument\x12!\n" +
	"\fprogram_name\x18\x01 \x01(\tR\vprogramName\x12'\n" +
	"\x0fprogram_version\x18\x02 \x01(\tR\x0eprogramVersion\x12=\n" +
	"\fgenerated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12!\n" +
	"\fgenerated_by\x18\x04 \x01(\tR\vgeneratedBy\x12*\n" +
	"\bsie_type\x18\x05 \x01(\x0e2\x0f.sie.v1.SieTypeR\asieType\x12/\n" +
	"\x13organisation_number\x18\x06 \x01(\tR\x12organisationNumber\x12!\n" +
	"\fcompany_name\x18\a \x01(\tR\vcompanyName\x12*\n" +
	"\x11chart_of_accounts\x18\b \x01(\tR\x0fchartOfAccounts\x12+\n" +
	"\baccounts\x18\t \x03(\v2\x0f.sie.v1.AccountR\baccounts\x12+\n" +
	"\bvouchers\x18\n" +
	" \x03(\v2\x0f.sie.v1.VoucherR\bvouchers\x12L\n" +
	"\x14financial_year_start\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x12financialYearStart\x12H\n" +
	"\x12financial_year_end\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x10financialYearEnd\x121\n" +
	"\n" +
	"dimensions\x18\r \x03(\v2\x11.sie.v1.DimensionR\n" +
	"dimensions\"\xd2\x01\n" +
	"\aAccount\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.sie.v1.AccountTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x128\n" +
	"\x0fopening_balance\x18\x04 \x01(\v2\x0f.sie.v1.DecimalR\x0eopeningBalance\x128\n" +
	"\x0fclosing_balance\x18\x05 \x01(\v2\x0f.sie.v1.DecimalR\x0eclosingBalance\"\xfd\x01\n" +
	"\aVoucher\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x16\n" +
	"\x06series\x18\x02 \x01(\tR\x06series\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12C\n" +
	"\x0fregistered_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0eregisteredDate\x12+\n" +
	"\bpostings\x18\x06 \x03(\v2\x0f.sie.v1.PostingR\bpostings\"\x8c\x01\n" +
	"\aPosting\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\x05R\raccountNumber\x121\n" +
	"\n" +
	"dimensions\x18\x02 \x03(\v2\x11.sie.v1.DimensionR\n" +
	"dimensions\x12'\n" +
	"\x06amount\x18\x03 \x01(\v2\x0f.sie.v1.DecimalR\x06amount\"X\n" +
	"\tDimension\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x1f\n" +
	"\vobject_code\x18\x02 \x01(\tR\n" +
	"objectCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name*\x9a\x01\n" +
	"\aSieType\x12\x18\n" +
	"\x14SIE_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSIE_TYPE_YEAR_END_BALANCES\x10\x01\x12\x1c\n" +
	"\x18SIE_TYPE_PERIOD_BALANCES\x10\x02\x12\x1c\n" +
	"\x18SIE_TYPE_OBJECT_BALANCES\x10\x03\x12\x19\n" +
	"\x15SIE_TYPE_TRANSACTIONS\x10\x04*\x92\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ACCOUNT_TYPE_ASSET\x10\x01\x12\x1a\n" +
	"\x16ACCOUNT_TYPE_LIABILITY\x10\x02\x12\x18\n" +
	"\x14ACCOUNT_TYPE_EXPENSE\x10\x03\x12\x17\n" +
	"\x13ACCOUNT_TYPE_INCOME\x10\x04B\x18Z\x16kastelo.dev/sie/v2;sieb\x06proto3"

var (
	file_sie_proto_rawDescOnce sync.Once
	file_sie_proto_rawDescData []byte
)

func file_sie_proto_rawDescGZIP() []byte {
	file_sie_proto_rawDescOnce.Do(func() {
		file_sie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sie_proto_rawDesc), len(file_sie_proto_rawDesc)))
	})
	return file_sie_proto_rawDescData
}

var file_sie_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sie_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sie_proto_goTypes = []any{
	(SieType)(0),                  // 0: sie.v1.SieType
	(AccountType)(0),              // 1: sie.v1.AccountType
	(*Decimal)(nil),               // 2: sie.v1.Decimal
	(*Document)(nil),              // 3: sie.v1.Document
	(*Account)(nil),               // 4: sie.v1.Account
	(*Voucher)(nil),               // 5: sie.v1.Voucher
	(*Posting)(nil),               // 6: sie.v1.Posting
	(*Dimension)(nil),             // 7: sie.v1.Dimension
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_sie_proto_depIdxs = []int32{
	8,  // 0: sie.v1.Document.generated_at:type_name -> google.protobuf.Timestamp
	0,  // 1: sie.v1.Document.sie_type:type_name -> sie.v1.SieType
	4,  // 2: sie.v1.Document.accounts:type_name -> sie.v1.Account
	5,  // 3: sie.v1.Document.vouchers:type_name -> sie.v1.Voucher
	8,  // 4: sie.v1.Document.financial_year_start:type_name -> google.protobuf.Timestamp
	8,  // 5: sie.v1.Document.financial_year_end:type_name -> google.protobuf.Timestamp
	7,  // 6: sie.v1.Document.dimensions:type_name -> sie.v1.Dimension
	1,  // 7: sie.v1.Account.type:type_name -> sie.v1.AccountType
	2,  // 8: sie.v1.Account.opening_balance:type_name -> sie.v1.Decimal
	2,  // 9: sie.v1.Account.closing_balance:type_name -> sie.v1.Decimal
	8,  // 10: sie.v1.Voucher.date:type_name -> google.protobuf.Timestamp
	8,  // 11: sie.v1.Voucher.registered_date:type_name -> google.protobuf.Timestamp
	6,  // 12: sie.v1.Voucher.postings:type_name -> sie.v1.Posting
	7,  // 13: sie.v1.Posting.dimensions:type_name -> sie.v1.Dimension
	2,  // 14: sie.v1.Posting.amount:type_name -> sie.v1.Decimal
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_sie_proto_init() }
func file_sie_proto_init() {
	if File_sie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sie_proto_rawDesc), len(file_sie_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sie_proto_goTypes,
		DependencyIndexes: file_sie_proto_depIdxs,
		EnumInfos:         file_sie_proto_enumTypes,
		MessageInfos:      file_sie_proto_msgTypes,
	}.Build()
	File_sie_proto = out.File
	file_sie_proto_goTypes = nil
	file_sie_proto_depIdxs = nil
}
