// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sie.proto

package sie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramName    string                 `protobuf:"bytes,1,opt,name=program_name,json=programName,proto3" json:"program_name,omitempty"`
	ProgramVersion string                 `protobuf:"bytes,2,opt,name=program_version,json=programVersion,proto3" json:"program_version,omitempty"`
	GeneratedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	GeneratedBy    string                 `protobuf:"bytes,4,opt,name=generated_by,json=generatedBy,proto3" json:"generated_by,omitempty"`
	Type           string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	OrgNo          string                 `protobuf:"bytes,6,opt,name=org_no,json=orgNo,proto3" json:"org_no,omitempty"`
	CompanyName    string                 `protobuf:"bytes,7,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	AccountPlan    string                 `protobuf:"bytes,8,opt,name=account_plan,json=accountPlan,proto3" json:"account_plan,omitempty"`
	Accounts       []*Account             `protobuf:"bytes,9,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Entries        []*Entry               `protobuf:"bytes,10,rep,name=entries,proto3" json:"entries,omitempty"`
	Starts         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=starts,proto3" json:"starts,omitempty"`
	Ends           *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=ends,proto3" json:"ends,omitempty"`
	Annotations    []*Annotation          `protobuf:"bytes,13,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_sie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_sie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *Document) GetProgramVersion() string {
	if x != nil {
		return x.ProgramVersion
	}
	return ""
}

func (x *Document) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *Document) GetGeneratedBy() string {
	if x != nil {
		return x.GeneratedBy
	}
	return ""
}

func (x *Document) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Document) GetOrgNo() string {
	if x != nil {
		return x.OrgNo
	}
	return ""
}

func (x *Document) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Document) GetAccountPlan() string {
	if x != nil {
		return x.AccountPlan
	}
	return ""
}

func (x *Document) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *Document) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Document) GetStarts() *timestamppb.Timestamp {
	if x != nil {
		return x.Starts
	}
	return nil
}

func (x *Document) GetEnds() *timestamppb.Timestamp {
	if x != nil {
		return x.Ends
	}
	return nil
}

func (x *Document) GetAnnotations() []*Annotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type Account struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type        string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Amount in cents.
	InBalance     *Decimal `protobuf:"bytes,4,opt,name=in_balance,json=inBalance,proto3" json:"in_balance,omitempty"`
	OutBalance    *Decimal `protobuf:"bytes,5,opt,name=out_balance,json=outBalance,proto3" json:"out_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_sie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_sie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Account) GetInBalance() *Decimal {
	if x != nil {
		return x.InBalance
	}
	return nil
}

func (x *Account) GetOutBalance() *Decimal {
	if x != nil {
		return x.OutBalance
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Filed         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=filed,proto3" json:"filed,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,6,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_sie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_sie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{2}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entry) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Entry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Entry) GetFiled() *timestamppb.Timestamp {
	if x != nil {
		return x.Filed
	}
	return nil
}

func (x *Entry) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Annotations   []*Annotation          `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Amount        *Decimal               `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_sie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_sie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{3}
}

func (x *Transaction) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Transaction) GetAnnotations() []*Annotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Transaction) GetAmount() *Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

type Annotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           int32                  `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Annotation) Reset() {
	*x = Annotation{}
	mi := &file_sie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Annotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Annotation) ProtoMessage() {}

func (x *Annotation) ProtoReflect() protoreflect.Message {
	mi := &file_sie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Annotation.ProtoReflect.Descriptor instead.
func (*Annotation) Descriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{4}
}

func (x *Annotation) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *Annotation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Annotation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Decimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cents         int64                  `protobuf:"zigzag64,1,opt,name=cents,proto3" json:"cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	mi := &file_sie_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_sie_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_sie_proto_rawDescGZIP(), []int{5}
}

func (x *Decimal) GetCents() int64 {
	if x != nil {
		return x.Cents
	}
	return 0
}

var File_sie_proto protoreflect.FileDescriptor

const file_sie_proto_rawDesc = "" +
	"\n" +
	"\tsie.proto\x12\x03sie\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x04\n" +
	"\bDocument\x12!\n" +
	"\fprogram_name\x18\x01 \x01(\tR\vprogramName\x12'\n" +
	"\x0fprogram_version\x18\x02 \x01(\tR\x0eprogramVersion\x12=\n" +
	"\fgenerated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12!\n" +
	"\fgenerated_by\x18\x04 \x01(\tR\vgeneratedBy\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x15\n" +
	"\x06org_no\x18\x06 \x01(\tR\x05orgNo\x12!\n" +
	"\fcompany_name\x18\a \x01(\tR\vcompanyName\x12!\n" +
	"\faccount_plan\x18\b \x01(\tR\vaccountPlan\x12(\n" +
	"\baccounts\x18\t \x03(\v2\f.sie.AccountR\baccounts\x12$\n" +
	"\aentries\x18\n" +
	" \x03(\v2\n" +
	".sie.EntryR\aentries\x122\n" +
	"\x06starts\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x06starts\x12.\n" +
	"\x04ends\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x04ends\x121\n" +
	"\vannotations\x18\r \x03(\v2\x0f.sie.AnnotationR\vannotations\"\xab\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12+\n" +
	"\n" +
	"in_balance\x18\x04 \x01(\v2\f.sie.DecimalR\tinBalance\x12-\n" +
	"\vout_balance\x18\x05 \x01(\v2\f.sie.DecimalR\n" +
	"outBalance\"\xe5\x01\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x120\n" +
	"\x05filed\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05filed\x124\n" +
	"\ftransactions\x18\x06 \x03(\v2\x10.sie.TransactionR\ftransactions\"\x85\x01\n" +
	"\vTransaction\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x05R\taccountId\x121\n" +
	"\vannotations\x18\x02 \x03(\v2\x0f.sie.AnnotationR\vannotations\x12$\n" +
	"\x06amount\x18\x03 \x01(\v2\f.sie.DecimalR\x06amount\"T\n" +
	"\n" +
	"Annotation\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\x05R\x03tag\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x1f\n" +
	"\aDecimal\x12\x14\n" +
	"\x05cents\x18\x01 \x01(\x12R\x05centsB\x11Z\x0fkastelo.dev/sieb\x06proto3"

var (
	file_sie_proto_rawDescOnce sync.Once
	file_sie_proto_rawDescData []byte
)

func file_sie_proto_rawDescGZIP() []byte {
	file_sie_proto_rawDescOnce.Do(func() {
		file_sie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sie_proto_rawDesc), len(file_sie_proto_rawDesc)))
	})
	return file_sie_proto_rawDescData
}

var file_sie_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sie_proto_goTypes = []any{
	(*Document)(nil),              // 0: sie.Document
	(*Account)(nil),               // 1: sie.Account
	(*Entry)(nil),                 // 2: sie.Entry
	(*Transaction)(nil),           // 3: sie.Transaction
	(*Annotation)(nil),            // 4: sie.Annotation
	(*Decimal)(nil),               // 5: sie.Decimal
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_sie_proto_depIdxs = []int32{
	6,  // 0: sie.Document.generated_at:type_name -> google.protobuf.Timestamp
	1,  // 1: sie.Document.accounts:type_name -> sie.Account
	2,  // 2: sie.Document.entries:type_name -> sie.Entry
	6,  // 3: sie.Document.starts:type_name -> google.protobuf.Timestamp
	6,  // 4: sie.Document.ends:type_name -> google.protobuf.Timestamp
	4,  // 5: sie.Document.annotations:type_name -> sie.Annotation
	5,  // 6: sie.Account.in_balance:type_name -> sie.Decimal
	5,  // 7: sie.Account.out_balance:type_name -> sie.Decimal
	6,  // 8: sie.Entry.date:type_name -> google.protobuf.Timestamp
	6,  // 9: sie.Entry.filed:type_name -> google.protobuf.Timestamp
	3,  // 10: sie.Entry.transactions:type_name -> sie.Transaction
	4,  // 11: sie.Transaction.annotations:type_name -> sie.Annotation
	5,  // 12: sie.Transaction.amount:type_name -> sie.Decimal
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_sie_proto_init() }
func file_sie_proto_init() {
	if File_sie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sie_proto_rawDesc), len(file_sie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sie_proto_goTypes,
		DependencyIndexes: file_sie_proto_depIdxs,
		MessageInfos:      file_sie_proto_msgTypes,
	}.Build()
	File_sie_proto = out.File
	file_sie_proto_goTypes = nil
	file_sie_proto_depIdxs = nil
}
